// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v2

import (
	"context"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"MyTodo/model/po/v1"
)

func newPostFavorite(db *gorm.DB, opts ...gen.DOOption) postFavorite {
	_postFavorite := postFavorite{}

	_postFavorite.postFavoriteDo.UseDB(db, opts...)
	_postFavorite.postFavoriteDo.UseModel(&po.PostFavorite{})

	tableName := _postFavorite.postFavoriteDo.TableName()
	_postFavorite.ALL = field.NewAsterisk(tableName)
	_postFavorite.ID = field.NewUint(tableName, "id")
	_postFavorite.CreatedAt = field.NewTime(tableName, "created_at")
	_postFavorite.UpdatedAt = field.NewTime(tableName, "updated_at")
	_postFavorite.DeletedAt = field.NewField(tableName, "deleted_at")
	_postFavorite.PID = field.NewUint(tableName, "pid")
	_postFavorite.UID = field.NewUint(tableName, "uid")

	_postFavorite.fillFieldMap()

	return _postFavorite
}

type postFavorite struct {
	postFavoriteDo

	ALL       field.Asterisk
	ID        field.Uint
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	PID       field.Uint
	UID       field.Uint

	fieldMap map[string]field.Expr
}

func (p postFavorite) Table(newTableName string) *postFavorite {
	p.postFavoriteDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p postFavorite) As(alias string) *postFavorite {
	p.postFavoriteDo.DO = *(p.postFavoriteDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *postFavorite) updateTableName(table string) *postFavorite {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewUint(table, "id")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.DeletedAt = field.NewField(table, "deleted_at")
	p.PID = field.NewUint(table, "pid")
	p.UID = field.NewUint(table, "uid")

	p.fillFieldMap()

	return p
}

func (p *postFavorite) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *postFavorite) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 6)
	p.fieldMap["id"] = p.ID
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["deleted_at"] = p.DeletedAt
	p.fieldMap["pid"] = p.PID
	p.fieldMap["uid"] = p.UID
}

func (p postFavorite) clone(db *gorm.DB) postFavorite {
	p.postFavoriteDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p postFavorite) replaceDB(db *gorm.DB) postFavorite {
	p.postFavoriteDo.ReplaceDB(db)
	return p
}

type postFavoriteDo struct{ gen.DO }

type IPostFavoriteDo interface {
	gen.SubQuery
	Debug() IPostFavoriteDo
	WithContext(ctx context.Context) IPostFavoriteDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPostFavoriteDo
	WriteDB() IPostFavoriteDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPostFavoriteDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPostFavoriteDo
	Not(conds ...gen.Condition) IPostFavoriteDo
	Or(conds ...gen.Condition) IPostFavoriteDo
	Select(conds ...field.Expr) IPostFavoriteDo
	Where(conds ...gen.Condition) IPostFavoriteDo
	Order(conds ...field.Expr) IPostFavoriteDo
	Distinct(cols ...field.Expr) IPostFavoriteDo
	Omit(cols ...field.Expr) IPostFavoriteDo
	Join(table schema.Tabler, on ...field.Expr) IPostFavoriteDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPostFavoriteDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPostFavoriteDo
	Group(cols ...field.Expr) IPostFavoriteDo
	Having(conds ...gen.Condition) IPostFavoriteDo
	Limit(limit int) IPostFavoriteDo
	Offset(offset int) IPostFavoriteDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPostFavoriteDo
	Unscoped() IPostFavoriteDo
	Create(values ...*po.PostFavorite) error
	CreateInBatches(values []*po.PostFavorite, batchSize int) error
	Save(values ...*po.PostFavorite) error
	First() (*po.PostFavorite, error)
	Take() (*po.PostFavorite, error)
	Last() (*po.PostFavorite, error)
	Find() ([]*po.PostFavorite, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*po.PostFavorite, err error)
	FindInBatches(result *[]*po.PostFavorite, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*po.PostFavorite) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPostFavoriteDo
	Assign(attrs ...field.AssignExpr) IPostFavoriteDo
	Joins(fields ...field.RelationField) IPostFavoriteDo
	Preload(fields ...field.RelationField) IPostFavoriteDo
	FirstOrInit() (*po.PostFavorite, error)
	FirstOrCreate() (*po.PostFavorite, error)
	FindByPage(offset int, limit int) (result []*po.PostFavorite, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPostFavoriteDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	FilterWithNameAndRole(name string, role string) (result []po.PostFavorite, err error)
}

// SELECT * FROM @@table WHERE name = @name{{if role !=""}} AND role = @role{{end}}
func (p postFavoriteDo) FilterWithNameAndRole(name string, role string) (result []po.PostFavorite, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, name)
	generateSQL.WriteString("SELECT * FROM post_favorite WHERE name = ? ")
	if role != "" {
		params = append(params, role)
		generateSQL.WriteString("AND role = ? ")
	}

	var executeSQL *gorm.DB
	executeSQL = p.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (p postFavoriteDo) Debug() IPostFavoriteDo {
	return p.withDO(p.DO.Debug())
}

func (p postFavoriteDo) WithContext(ctx context.Context) IPostFavoriteDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p postFavoriteDo) ReadDB() IPostFavoriteDo {
	return p.Clauses(dbresolver.Read)
}

func (p postFavoriteDo) WriteDB() IPostFavoriteDo {
	return p.Clauses(dbresolver.Write)
}

func (p postFavoriteDo) Session(config *gorm.Session) IPostFavoriteDo {
	return p.withDO(p.DO.Session(config))
}

func (p postFavoriteDo) Clauses(conds ...clause.Expression) IPostFavoriteDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p postFavoriteDo) Returning(value interface{}, columns ...string) IPostFavoriteDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p postFavoriteDo) Not(conds ...gen.Condition) IPostFavoriteDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p postFavoriteDo) Or(conds ...gen.Condition) IPostFavoriteDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p postFavoriteDo) Select(conds ...field.Expr) IPostFavoriteDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p postFavoriteDo) Where(conds ...gen.Condition) IPostFavoriteDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p postFavoriteDo) Order(conds ...field.Expr) IPostFavoriteDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p postFavoriteDo) Distinct(cols ...field.Expr) IPostFavoriteDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p postFavoriteDo) Omit(cols ...field.Expr) IPostFavoriteDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p postFavoriteDo) Join(table schema.Tabler, on ...field.Expr) IPostFavoriteDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p postFavoriteDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPostFavoriteDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p postFavoriteDo) RightJoin(table schema.Tabler, on ...field.Expr) IPostFavoriteDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p postFavoriteDo) Group(cols ...field.Expr) IPostFavoriteDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p postFavoriteDo) Having(conds ...gen.Condition) IPostFavoriteDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p postFavoriteDo) Limit(limit int) IPostFavoriteDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p postFavoriteDo) Offset(offset int) IPostFavoriteDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p postFavoriteDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPostFavoriteDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p postFavoriteDo) Unscoped() IPostFavoriteDo {
	return p.withDO(p.DO.Unscoped())
}

func (p postFavoriteDo) Create(values ...*po.PostFavorite) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p postFavoriteDo) CreateInBatches(values []*po.PostFavorite, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p postFavoriteDo) Save(values ...*po.PostFavorite) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p postFavoriteDo) First() (*po.PostFavorite, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*po.PostFavorite), nil
	}
}

func (p postFavoriteDo) Take() (*po.PostFavorite, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*po.PostFavorite), nil
	}
}

func (p postFavoriteDo) Last() (*po.PostFavorite, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*po.PostFavorite), nil
	}
}

func (p postFavoriteDo) Find() ([]*po.PostFavorite, error) {
	result, err := p.DO.Find()
	return result.([]*po.PostFavorite), err
}

func (p postFavoriteDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*po.PostFavorite, err error) {
	buf := make([]*po.PostFavorite, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p postFavoriteDo) FindInBatches(result *[]*po.PostFavorite, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p postFavoriteDo) Attrs(attrs ...field.AssignExpr) IPostFavoriteDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p postFavoriteDo) Assign(attrs ...field.AssignExpr) IPostFavoriteDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p postFavoriteDo) Joins(fields ...field.RelationField) IPostFavoriteDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p postFavoriteDo) Preload(fields ...field.RelationField) IPostFavoriteDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p postFavoriteDo) FirstOrInit() (*po.PostFavorite, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*po.PostFavorite), nil
	}
}

func (p postFavoriteDo) FirstOrCreate() (*po.PostFavorite, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*po.PostFavorite), nil
	}
}

func (p postFavoriteDo) FindByPage(offset int, limit int) (result []*po.PostFavorite, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p postFavoriteDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p postFavoriteDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p postFavoriteDo) Delete(models ...*po.PostFavorite) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *postFavoriteDo) withDO(do gen.Dao) *postFavoriteDo {
	p.DO = *do.(*gen.DO)
	return p
}
