# Copyright 2025 The MyTodo Authors. All rights reserved.
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file.
version: '3'
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  redis:
    image: redis
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456

  # rabbitmq:
  #   image: rabbitmq:management
  #   ports:
  #     - "15672:15672"
  #     - "5672:5672"
  #   environment:
  #     RABBITMQ_DEFAULT_USER: root
  #     RABBITMQ_DEFAULT_PASS: 123456

  # es:
  #   image: elasticsearch:8.10.2
  #   container_name: es
  #   restart: always
  #   network_mode: es
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"
  #   privileged: true
  #   environment:
  #     - discovery.type=single-node
  #     - ES_JAVA_OPTS=-Xms512m -Xmx512m
  #   volumes:
  #     - /home/es/data:/usr/share/elasticsearch/data
  #     - /home/es/plugins:/usr/share/elasticsearch/plugins
  #     - /home/es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  
  # kibana:
  #   image: kibana:8.10.2
  #   ports:
  #     - "5601:5601"
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #     - NODE_OPTIONS=--openssl-legacy-provider
  #   volumes:
  #     - /home/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
  #   networks:
  #     - es
  #   depends_on:
  #     - es

  # etcd:
  #   image: bitnami/etcd
  #   ports:
  #     - "2379:2379"
  #     - "2380:2380"
  #   environment:
  #     - ALLOW_NONE_AUTHENTICATION=yes
  #     - ETCD_ADVERTISE_CLIENT_URLS=https://etcd-server:2379

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      - MINIO_ACCESS_KEY=root
      - MINIO_SECRET_KEY=root123456
    volumes:
      - /home/minio/data:/data
      - /home/minio/config:/root/.minio
    restart: always
    command: server /data --console-address ":9090" --address ":9000"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9091:9090"
      - "9100:9100"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/todo/prom/data:/prometheus/data
      - ~/todo/prom/config:/etc/prometheus
      - ~/todo/prom/rules:/prometheus/rules
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
    restart: always

networks:
  backend:
    driver: bridge
